Repository apache/maven-compiler-plugin, pull requests merged in 2022-02, with the labels that each got.

#92 use plexus-compiler 2.10.0
  pom.xml
Labels: dependencies

#93 add more jdk for testing
  .github/workflows/maven-verify.yml
Labels: build

#95 [MCOMPILER-485] Fixes internal string format in generated package-info.class
  src/it/MCOMPILER-485/invoker.properties
  src/it/MCOMPILER-485/pom.xml
  src/it/MCOMPILER-485/src/main/java/dummy/HelloWorld.java
  src/it/MCOMPILER-485/src/main/java/dummy/package-info.java
  src/it/MCOMPILER-485/verify.groovy
  src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
Labels: bug
