Repository apache/maven-compiler-plugin, pull requests merged in 2023-06, with the labels that each got.

#189 [MNG-6829] Replace StringUtils#isEmpty(String) & #isNotEmpty(String)
  src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
Labels: java, maintenance

#180 [MCOMPILER-391] Use dep mgmt when resolving annotation processors and their deps
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-api/pom.xml
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-api/src/main/java/mcompiler391/SimpleAnnotation.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor-dep-v1/pom.xml
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor-dep-v1/src/main/java/mcompiler391/AnnotationProcessorDependencyV1.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor-dep-v2/pom.xml
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor-dep-v2/src/main/java/mcompiler391/AnnotationProcessorDependencyV2.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor/pom.xml
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-processor/src/main/java/mcompiler391/SimpleAnnotationProcessor.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user1/pom.xml
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user1/src/main/java/mcompiler391/SimpleObject1.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user1/src/test/java/mcompiler391/SimpleTestObject1.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user2/pom.xml
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user2/src/main/java/mcompiler391/SimpleObject2.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user2/src/test/java/mcompiler391/SimpleTestObject2.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user3/pom.xml
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user3/src/main/java/mcompiler391/SimpleObject3.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user3/src/test/java/mcompiler391/SimpleTestObject3.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user4/pom.xml
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user4/src/main/java/mcompiler391/SimpleObject4.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/annotation-user4/src/test/java/mcompiler391/SimpleTestObject4.java
  src/it/MCOMPILER-391-processorpath-dep-mgmt/invoker.properties
  src/it/MCOMPILER-391-processorpath-dep-mgmt/pom.xml
  src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
Labels: enhancement

#190 (doc) Drop unused and vulnerable dependency to log4j
  src/it/mcompiler-120/pom.xml
Labels: maintenance
