Repository apache/maven-compiler-plugin, pull requests merged in 2025-06, with the labels that each got.

#328 Bump org.apache.maven.plugins:maven-plugins from 43 to 44
  pom.xml
  src/test/java/org/apache/maven/plugin/compiler/CompilerMojoTestCase.java
  src/test/java/org/apache/maven/plugin/compiler/stubs/CompilerStub.java
Labels: dependencies

#331 Allow to not use --module-version for the Java compiler
  src/it/GH-331-no-module-version/invoker.properties
  src/it/GH-331-no-module-version/pom.xml
  src/it/GH-331-no-module-version/src/main/java/com/foo/MyClass.java
  src/it/GH-331-no-module-version/src/main/java/module-info.java
  src/it/GH-331-no-module-version/verify.groovy
  src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java
Labels: enhancement

#939 Add JDK 23 information and example for annotation processing
  src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
  src/site/markdown/examples/annotation-processor.md
  src/site/site.xml
Labels: documentation
