Repository apache/maven-compiler-plugin, pull requests merged in 2025-02, with the labels that each got.

#278 Add PR automation
  .github/workflows/pr-automation.yml
Labels: enhancement

#280 Disable Jenkins build
  Jenkinsfile.disable
  README.md
Labels: maintenance

#279 Add dependabot for 3.x branch
  .github/dependabot.yml
Labels: enhancement

#289 Use default Maven versions for build on GitHub
  .github/workflows/maven-verify.yml
Labels: maintenance

#292 Fix release-drafter config
  .github/workflows/release-drafter.yml
Labels: bug

#298 Simplify GH action
  .github/workflows/maven-verify.yml
Labels: maintenance

#297 Add badge for 3.x version
  README.md
Labels: maintenance

#296 [MNGSITE-529] Rename "Goals" to "Plugin Documentation"
  src/site/site.xml
Labels: documentation

#299 Use JUnit version from parent
  pom.xml
Labels: maintenance

#302 Rename property `moduleVersion` to `maven.compiler.moduleVersion`
  src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java
Labels: maintenance

#273 [MCOMPILER-579] allow module-version configuration
  pom.xml
  src/main/java/org/apache/maven/plugin/compiler/CompilerMojo.java
Labels: enhancement

#301 Publish documentation to LATEST-4.x
  pom.xml
Labels: maintenance

#305 Enable GitHub Issues
  README.md
  pom.xml
Labels: enhancement
